"""Receipt entry view construction; orchestration stays in MainWindow."""
from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QComboBox, QFormLayout, QGroupBox, QHBoxLayout, QGridLayout,
    QHeaderView, QLabel, QListWidget, QMenu, QPushButton,
    QProgressBar, QScrollArea, QSplitter, QTableWidget, QVBoxLayout, QWidget,
)
from appearance import ReceiptCheckDelegate
from core import CATEGORIES
from image_viewer import ImageViewer


def build(self, field) -> QWidget:
    root = QWidget()
    layout = QVBoxLayout(root)
    top = QHBoxLayout()
    self.add_images_btn = QPushButton("画像を追加")
    self.add_images_btn.clicked.connect(self._add_images)
    self.read_btn = QPushButton("選択中を読み取る")
    self.read_btn.setObjectName("primary")
    self.read_btn.clicked.connect(self._read_image)
    self.new_btn = QPushButton("新規入力")
    self.new_btn.clicked.connect(lambda: self._new_form())
    self.batch_read_btn = QPushButton("未読を一括読み込み")
    self.batch_read_btn.setToolTip("一覧の絞り込みに関係なく、すべての未読画像を読み取ります。")
    self.batch_read_btn.clicked.connect(self._read_batch)
    self.retry_btn = QPushButton("失敗分を再試行")
    self.retry_btn.setToolTip("一覧の絞り込みに関係なく、すべての読取失敗画像を再試行します。")
    self.retry_btn.clicked.connect(self._retry_failed)
    self.stop_btn = QPushButton("停止")
    self.stop_btn.setEnabled(False)
    self.stop_btn.clicked.connect(self._stop_batch)
    top.addWidget(self.add_images_btn)
    top.addWidget(self.read_btn)
    top.addWidget(self.batch_read_btn)
    top.addWidget(self.retry_btn)
    top.addWidget(self.stop_btn)
    top.addWidget(self.new_btn)
    top.addStretch()
    layout.addLayout(top)
    progress_row = QHBoxLayout()
    self.batch_progress = QProgressBar()
    self.batch_progress.setRange(0, 1)
    self.batch_progress.setValue(0)
    self.batch_progress.setMaximumWidth(240)
    self.batch_status = QLabel("複数画像を追加して、一括読み込みを開始できます。")
    self.batch_status.setWordWrap(True)
    self.batch_status.setTextFormat(Qt.TextFormat.PlainText)
    progress_row.addWidget(self.batch_progress)
    progress_row.addWidget(self.batch_status, 1)
    layout.addLayout(progress_row)
    splitter = QSplitter(Qt.Orientation.Horizontal)
    left = QWidget()
    left_layout = QVBoxLayout(left)
    self.queue = QListWidget()
    self.queue_delegate = ReceiptCheckDelegate(self.queue)
    self.queue.setItemDelegate(self.queue_delegate)
    self.queue.setMaximumHeight(180)
    self.queue.currentRowChanged.connect(self._select_queue_image)
    self.queue.itemChanged.connect(self._queue_item_changed)
    left_layout.addWidget(QLabel("取り込んだ画像（記録・一覧から削除する画像にチェック）"))
    filter_row = QHBoxLayout()
    self.queue_filter = QComboBox()
    self.queue_filter.setAccessibleName("画像一覧の状態で絞り込み")
    for label, state in (("すべて", "all"), ("未読取", "pending"), ("確認待ち", "ready"),
                         ("読取失敗", "failed"), ("記録済み", "saved")):
        self.queue_filter.addItem(label, state)
    self.queue_search = field("画像一覧を検索", "店舗名・ファイル名で検索")
    self.queue_search.setClearButtonEnabled(True)
    self.queue_filter.currentIndexChanged.connect(self._queue_filter_changed)
    self.queue_search.textChanged.connect(self._queue_filter_changed)
    filter_row.addWidget(self.queue_filter)
    filter_row.addWidget(self.queue_search, 1)
    left_layout.addLayout(filter_row)
    selection_row = QHBoxLayout()
    self.check_visible_btn = QPushButton("表示中をすべてチェック")
    self.check_visible_btn.setToolTip("表示中の未読・失敗・確認待ち・記録済み画像をチェックします。読み取り中と読み取りの開始待ちの画像は対象外です。")
    self.check_visible_btn.clicked.connect(self._check_visible)
    self.clear_checks_btn = QPushButton("チェックをすべて解除")
    self.clear_checks_btn.setToolTip("非表示のレシートも含めてチェックを解除します。")
    self.clear_checks_btn.clicked.connect(self._clear_checks)
    selection_row.addWidget(self.check_visible_btn)
    selection_row.addWidget(self.clear_checks_btn)
    self.remove_images_btn = QPushButton("一覧から削除…")
    self.remove_images_btn.setToolTip("画像一覧と下書きから削除します。元画像・Excelの記録は残ります。読み取り・接続処理中は利用できません。")
    remove_menu = QMenu(self.remove_images_btn)
    self.remove_image_actions = {}
    for scope in ("current", "checked", "visible"):
        action = remove_menu.addAction("")
        action.triggered.connect(lambda _checked=False, scope=scope: self._remove_images(scope))
        self.remove_image_actions[scope] = action
    self.remove_images_btn.setMenu(remove_menu)
    selection_row.addWidget(self.remove_images_btn)
    selection_row.addStretch()
    left_layout.addLayout(selection_row)
    left_layout.addWidget(self.queue)
    self.review_count_label = QLabel("選択 0 件（未記録 0 件・記録済み 0 件）")
    self.review_count_label.setWordWrap(True)
    left_layout.addWidget(self.review_count_label)
    removal_row = QHBoxLayout()
    self.remove_checked_btn = QPushButton("選択 0 件を一覧から削除")
    self.remove_checked_btn.clicked.connect(lambda: self._remove_images("checked"))
    self.undo_remove_btn = QPushButton("削除を元に戻す")
    self.undo_remove_btn.setToolTip("直近10回の一覧からの削除を、新しい順に戻せます。再起動後も利用できます。")
    self.undo_remove_btn.clicked.connect(self._undo_remove_images)
    removal_row.addWidget(self.remove_checked_btn)
    removal_row.addWidget(self.undo_remove_btn)
    removal_row.addStretch()
    left_layout.addLayout(removal_row)
    self.queue_filter_notice = QLabel()
    self.queue_filter_notice.setTextFormat(Qt.TextFormat.PlainText)
    self.queue_filter_notice.setWordWrap(True)
    self.queue_filter_notice.hide()
    left_layout.addWidget(self.queue_filter_notice)
    self.batch_save_btn = QPushButton("未記録 0 件をExcelに記録")
    self.batch_save_btn.setObjectName("primary")
    self.batch_save_btn.clicked.connect(self._save_batch)
    self.preview = ImageViewer()
    left_layout.addWidget(self.preview, 1)
    splitter.addWidget(left)

    right = QWidget()
    self.receipt_editor = right
    right_layout = QVBoxLayout(right)
    info = QGroupBox("レシート情報")
    form = QGridLayout(info)
    self.date_edit = field("購入日", "YYYY-MM-DD")
    self.merchant_edit = field("店舗名")
    self.amount_edit = field("合計金額（税込）", "税込の支払合計、円の整数")
    self.tax_edit = field("うち消費税額", "不明なら空欄、0円なら0")
    self.tax_edit.setToolTip("税込合計に含まれる消費税額です。合計に再加算しません。")
    self.discount_edit = field("値引き額", "任意")
    self.category_box = QComboBox()
    self.category_box.addItems(CATEGORIES)
    self.payment_edit = field("支払方法")
    self.memo_edit = field("メモ")
    form.addWidget(QLabel("購入日 *"), 0, 0)
    form.addWidget(self.date_edit, 0, 1)
    form.addWidget(QLabel("費目 *"), 0, 2)
    form.addWidget(self.category_box, 0, 3)
    form.addWidget(QLabel("店舗名 *"), 1, 0)
    form.addWidget(self.merchant_edit, 1, 1, 1, 3)
    form.addWidget(QLabel("税込合計 *"), 2, 0)
    form.addWidget(self.amount_edit, 2, 1)
    form.addWidget(QLabel("うち消費税"), 2, 2)
    form.addWidget(self.tax_edit, 2, 3)
    form.setColumnStretch(1, 1)
    form.setColumnStretch(3, 1)
    right_layout.addWidget(info)
    self.details_toggle = QPushButton("その他の情報（支払方法・値引き・メモ）")
    self.details_toggle.setCheckable(True)
    self.details_fields = QWidget()
    details_form = QFormLayout(self.details_fields)
    for label, widget in (("支払方法", self.payment_edit), ("値引き額", self.discount_edit), ("メモ", self.memo_edit)):
        details_form.addRow(label, widget)
    self.details_fields.setVisible(False)
    self.details_toggle.toggled.connect(self.details_fields.setVisible)
    right_layout.addWidget(self.details_toggle)
    right_layout.addWidget(self.details_fields)

    item_group = QGroupBox("購入した商品（数量・単価・補足を確認）")
    item_layout = QVBoxLayout(item_group)
    self.item_table = QTableWidget(0, 5)
    self.item_table.setHorizontalHeaderLabels(["品目", "数量", "単価（円）", "金額（円）", "詳細・補足"])
    self.item_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.Stretch)
    self.item_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.Stretch)
    self.item_table.setMinimumHeight(170)
    item_layout.addWidget(self.item_table)
    item_hint = QLabel("金額が空欄なら数量 × 単価から計算します。規格・容量・税率などは「詳細・補足」に入力できます。")
    item_hint.setWordWrap(True)
    item_layout.addWidget(item_hint)
    item_actions = QHBoxLayout()
    add_item = QPushButton("行を追加")
    add_item.clicked.connect(lambda: self.item_table.insertRow(self.item_table.rowCount()))
    delete_item = QPushButton("選択行を削除")
    delete_item.clicked.connect(self._delete_item_rows)
    item_actions.addWidget(add_item)
    item_actions.addWidget(delete_item)
    item_actions.addStretch()
    item_layout.addLayout(item_actions)
    right_layout.addWidget(item_group, 1)
    self.warning_label = QLabel("読み取り後、元画像と金額を確認して登録してください。")
    self.warning_label.setWordWrap(True)
    self.warning_label.setObjectName("receiptWarning")
    right_layout.addWidget(self.warning_label)
    self.receipt_save_target = QLabel()
    self.receipt_save_target.setTextFormat(Qt.TextFormat.PlainText)
    self.save_btn = QPushButton("この1件を記録")
    self.save_btn.clicked.connect(self._save_receipt)
    right_scroll = QScrollArea()
    right_scroll.setWidgetResizable(True)
    right_scroll.setWidget(right)
    splitter.addWidget(right_scroll)
    splitter.setSizes([550, 680])
    layout.addWidget(splitter, 1)
    footer = QHBoxLayout()
    footer_info = QVBoxLayout()
    footer_info.addWidget(self.receipt_save_target)
    self.autosave_label = QLabel("下書きを自動保存します")
    self.autosave_label.setWordWrap(True)
    footer_info.addWidget(self.autosave_label)
    footer.addLayout(footer_info, 1)
    footer.addWidget(self.save_btn)
    footer.addWidget(self.batch_save_btn)
    layout.addLayout(footer)
    return root

