"""Settings view construction; orchestration stays in MainWindow."""
from pathlib import Path
from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QCheckBox, QComboBox, QFormLayout, QGroupBox, QHBoxLayout,
    QLabel, QLineEdit, QPushButton,
    QScrollArea, QVBoxLayout, QWidget, QSpinBox,
)
from config import app_data_dir, application_dir
from version import APP_VERSION


def build(self, field, token) -> QWidget:
    root = QWidget()
    layout = QVBoxLayout(root)
    appearance_group = QGroupBox("画面表示")
    appearance_form = QFormLayout(appearance_group)
    self.theme_box = self._theme_selector()
    appearance_form.addRow("表示モード（自動保存）", self.theme_box)
    layout.addWidget(appearance_group)
    server_group = QGroupBox("LM Studio サーバー")
    server_form = QFormLayout(server_group)
    self.url_edit = field("接続先", "http://192.168.1.10:1234/v1")
    self.url_edit.setText(self.settings.server_url)
    self.token_edit = field("認証トークン", "LM Studio で発行したトークン")
    self.token_edit.setEchoMode(QLineEdit.EchoMode.Password)
    self._saved_server_token = token
    self.token_edit.setText(self._saved_server_token)
    self.model_box = QComboBox()
    self.model_box.setEditable(True)
    self.model_box.addItems(self.settings.model_choices)
    self.model_box.setCurrentText(self.settings.model)
    self.model_box.activated.connect(self._save_model_selection)
    self.model_box.lineEdit().editingFinished.connect(self._save_model_selection)
    server_form.addRow("接続先 URL", self.url_edit)
    server_form.addRow("認証トークン", self.token_edit)
    server_form.addRow("モデル", self.model_box)
    self.concurrency_box = QComboBox()
    self.concurrency_box.addItem("1件（順番に解析）", 1)
    self.concurrency_box.addItem("2件（並列に解析）", 2)
    self.concurrency_box.setCurrentIndex(self.concurrency_box.findData(self.settings.concurrent_reads))
    self.concurrency_box.currentIndexChanged.connect(self._save_concurrency)
    server_form.addRow("同時解析数", self.concurrency_box)
    parallel_hint = QLabel("変更は自動保存され、次の読み取りから適用されます。2件ではGPUメモリの使用量が増えます。速度はサーバーの設定やモデルによって異なります。")
    parallel_hint.setWordWrap(True)
    server_form.addRow("", parallel_hint)
    connect_btn = QPushButton("接続テスト・モデル取得")
    connect_btn.clicked.connect(self._test_connection)
    server_form.addRow("", connect_btn)
    server_hint = QLabel("接続成功時にURL・認証情報・モデル一覧を自動保存します。接続後のモデル選択も保存し、次回起動時に復元します。")
    server_hint.setWordWrap(True)
    server_form.addRow("", server_hint)
    layout.addWidget(server_group)
    storage_group = QGroupBox("保存")
    storage_form = QFormLayout(storage_group)
    self.workbook_edit = field("Excel 保存先")
    self.workbook_edit.setText(self.settings.workbook_path)
    browse = QPushButton("選択")
    browse.clicked.connect(self._choose_workbook)
    path_row = QWidget()
    path_layout = QHBoxLayout(path_row)
    path_layout.setContentsMargins(0, 0, 0, 0)
    path_layout.addWidget(self.workbook_edit, 1)
    path_layout.addWidget(browse)
    storage_form.addRow("家計簿ファイル", path_row)
    self.keep_check = QCheckBox("元画像をアプリ専用フォルダに保存する")
    self.keep_check.setChecked(self.settings.keep_images)
    storage_form.addRow("", self.keep_check)
    self.image_folder_edit = field("記録済み画像の保存先")
    self.image_folder_edit.setText(self.settings.image_folder)
    image_row = QWidget()
    image_layout = QHBoxLayout(image_row)
    image_layout.setContentsMargins(0, 0, 0, 0)
    image_layout.addWidget(self.image_folder_edit, 1)
    image_browse = QPushButton("選択")
    image_browse.clicked.connect(self._choose_image_folder)
    image_layout.addWidget(image_browse)
    storage_form.addRow("画像の保存先", image_row)
    image_hint = QLabel("変更は今後の保存に適用します。以前の画像は元の保存先から引き続き表示します。")
    image_hint.setWordWrap(True)
    storage_form.addRow("", image_hint)
    open_row = QHBoxLayout()
    for label, getter in (("Excelのフォルダ", lambda: self.ledger.path.parent),
                          ("画像のフォルダ", lambda: Path(self.settings.image_folder)),
                          ("下書き・設定のフォルダ", app_data_dir)):
        button = QPushButton(label)
        button.clicked.connect(lambda _checked=False, getter=getter: self._open_folder(getter()))
        open_row.addWidget(button)
    storage_form.addRow("保存先を開く", open_row)
    self.backup_limit_spin = QSpinBox()
    self.backup_limit_spin.setRange(1, 999)
    self.backup_limit_spin.setMaximumWidth(160)
    self.backup_limit_spin.setSuffix(" 世代")
    self.backup_limit_spin.setValue(self.settings.backup_generations)
    storage_form.addRow("通常バックアップの保持数", self.backup_limit_spin)
    retention_hint = QLabel("Excel保存時に設定した世代数まで通常バックアップを整理します。削除前・復元前の退避と一括ZIPは自動削除しません。")
    retention_hint.setWordWrap(True)
    storage_form.addRow("", retention_hint)
    self.storage_usage_label = QLabel("「容量を確認」で保存データの件数・容量を表示します。")
    self.storage_usage_label.setWordWrap(True)
    self.storage_usage_label.setTextFormat(Qt.TextFormat.PlainText)
    storage_form.addRow("データ容量", self.storage_usage_label)
    usage_row = QHBoxLayout()
    usage_btn = QPushButton("容量を確認")
    usage_btn.clicked.connect(self._refresh_storage_usage)
    usage_row.addWidget(usage_btn)
    prune_btn = QPushButton("古い通常バックアップを整理")
    prune_btn.clicked.connect(self._prune_backups_now)
    usage_row.addWidget(prune_btn)
    storage_form.addRow("", usage_row)
    bundle_row = QHBoxLayout()
    self.export_bundle_btn = QPushButton("データ一式をバックアップ")
    self.export_bundle_btn.clicked.connect(self._export_bundle)
    self.import_bundle_btn = QPushButton("データ一式を復元")
    self.import_bundle_btn.clicked.connect(self._import_bundle)
    bundle_row.addWidget(self.export_bundle_btn)
    bundle_row.addWidget(self.import_bundle_btn)
    storage_form.addRow("一括バックアップ", bundle_row)
    restore_btn = QPushButton("バックアップから復元")
    restore_btn.clicked.connect(self._restore_backup)
    storage_form.addRow("", restore_btn)
    discard_btn = QPushButton("下書きと画像一覧を消去")
    discard_btn.clicked.connect(self._discard_session)
    storage_form.addRow("", discard_btn)
    layout.addWidget(storage_group)
    save_settings_btn = QPushButton("設定を保存")
    save_settings_btn.setObjectName("primary")
    save_settings_btn.clicked.connect(self._save_settings)
    layout.addWidget(save_settings_btn)
    hint = QLabel("読み取り画像は LAN 内の LM Studio に送信されます。Excel ファイルはこの PC に保存されます。")
    hint.setWordWrap(True)
    layout.addWidget(hint)
    diagnostics_group = QGroupBox("診断")
    diagnostics_layout = QVBoxLayout(diagnostics_group)
    diagnostics_hint = QLabel("処理時間・画像形式・失敗原因をローカルに記録します。画像、レシート本文、URL、認証情報は記録しません。ログは最大約2MBまで保持します。")
    diagnostics_hint.setWordWrap(True)
    diagnostics_layout.addWidget(diagnostics_hint)
    self.copy_diagnostics_btn = QPushButton("診断情報をコピー")
    self.copy_diagnostics_btn.clicked.connect(self._copy_diagnostics)
    diagnostics_layout.addWidget(self.copy_diagnostics_btn)
    layout.addWidget(diagnostics_group)
    version_group = QGroupBox(f"アプリ情報 — v{APP_VERSION}")
    version_layout = QVBoxLayout(version_group)
    executable_label = QLabel(f"アプリの場所: {application_dir()}")
    executable_label.setTextFormat(Qt.TextFormat.PlainText)
    executable_label.setWordWrap(True)
    version_layout.addWidget(executable_label)
    update_btn = QPushButton("更新手順を見る")
    update_btn.clicked.connect(self._show_update_guide)
    version_layout.addWidget(update_btn)
    layout.addWidget(version_group)
    layout.addStretch()
    scroll = QScrollArea()
    scroll.setWidgetResizable(True)
    scroll.setWidget(root)
    return scroll

